<?php

use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\URL;

?>

<div id="wrapper">
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
        <!-- Sidebar - Brand -->
        <a class="sidebar-brand d-flex align-items-center justify-content-left" href="index.html">
            <div class="sidebar-brand-icon ">
                <img src="<?= Asset::image('/myimgs/minilogo.jpg') ?>">
            </div>
        </a>

        <!-- Divider -->
        <hr class="sidebar-divider my-0 mt-2">

        <!-- Nav Item - Checkin -->
        <li class="nav-item">
            <a class="nav-link" href="<?= URL::toRoute('checkin/') ?>" aria-expanded="true">
                <i class="far fa-check-circle"></i>
                <span>Checkin</span>
            </a>
        </li>

        <!-- Nav Item - histórico -->
        <li class="nav-item">
            <a class="nav-link " href="<?= URL::toRoute('checkin/historico') ?>" aria-expanded="true">
                <i class="fas fa-list"></i>
                <span>Histórico</span>
            </a>
        </li>

        <!-- Nav Item - Perfil -->
        <li class="nav-item">
            <a class="nav-link" href="<?= URL::toRoute('user/perfil') ?>" aria-expanded="true">
                <i class="fas fa-users-cog"></i>
                <span>Perfil</span>
            </a>
        </li>

        <!-- Divider -->
        <hr class="sidebar-divider my-0">

        <!-- Logout -->
        <li class="nav-item">
            <a class="nav-link" href="<?= URL::toRoute('home/logout') ?>" aria-expanded="true">
                <i class="fas fa-sign-out-alt"></i>
                <span>Logout</span>
            </a>
        </li>
    </ul>
</div>