<?php   
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Data;
?>

<html>
<head>
    <meta charset="utf-8">
    <title>Teste log in page</title>
    <link rel="stylesheet" type="text/css" href="<?= Asset::css('login.css')?>">

</head>
<body>


<div id="image" style="height: 200px; width: 50%; position: center;">
    <img src="<?= Asset::image('/myimgs/logo.jpg')?>" alt="logo"> 
</div>
<div id="bodyform">
    <form action="<?php echo (Url::toRoute('home/login'));?>" method="POST">
        <input type="user" name="username" placeholder="Username">  
        <input type="password" name="password" placeholder="Password">
        <input type="submit" value="Log in">
        <strong>Sign In</strong></a>

    </form>
</div>
</body>
</html>