<?php

use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Data;

$airplanes = Data::get('airplanes');
$airplaneToEdit = Data::get('airplaneToEdit');

?>


<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Custom fonts for this template-->
    <link href="<?= Asset::css('/template/fontawesome-free/css/all.min.css') ?>" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,200,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="<?= Asset::css('/template/sb-admin-2.css') ?>" rel="stylesheet">
    <title>FlightTravelAir</title>
</head>

<body>
    <div id="wrapper">
        <!-- Sidebar -->
        <?php Layout::includeLayout('leftbarGestorVoo') ?>

        <div id="content-wrapper" class="d-flex flex-column">
            <div class="container-fluid">

                <!-- Page Heading -->
                <h1 class="h3 mt-3 mb-4 text-gray-800">Aviões</h1>

                <!-- mensagens de erro, sucesso e aviso -->
                <?php Layout::includeLayout('mensagens') ?>

                <!-- DataTales Example -->
                <div class="card shadow mb-4">
                    <div class="card-header py-3">
                        <i class="fas fa-list"></i> Lista Aviões
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                <thead>
                                    <tr>
                                        <th style="width: 30%">Referência</th>
                                        <th style="width: 30%">Lotação Avião</th>
                                        <th style="width: 30%">Tipo Avião</th>
                                        <th style="width: 10%">Ações</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php
                                    foreach ($airplanes as $airplane) { ?>
                                        <tr>
                                            <td><?= $airplane->referencia ?></td>
                                            <td><?= $airplane->lotacaototal ?></td>
                                            <td><?= $airplane->tipoaviao ?></td>
                                            <td>
                                                <!-- editar -->
                                                <form style="float: left; padding-right: 2px;" action="<?= Url::toRoute('aviao/editar', $airplane->idaviao) ?> " method="POST">
                                                    <button class="btn btn-info btn-circle btn-sm" type="submit">
                                                        <i class="fas fa-pencil-alt"></i>
                                                    </button>
                                                </form>
                                                <!-- eliminar -->
                                                <form style="float: left; padding-right: 2px;" action="<?= Url::toRoute('aviao/eliminar', $airplane->idaviao) ?>" method="POST">
                                                    <button class="btn btn-danger btn-circle btn-sm" type="submit">
                                                        <i class="fas fa-trash-alt"></i>
                                                    </button>
                                                </form>
                                            </td>
                                        </tr>
                                    <?php } ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>

                <!-- ADD AVIOES -->
                <div class="card shadow mb-4">
                    <div class="card-header py-3">
                        <?php if (is_null($airplaneToEdit)) {
                        ?>
                            <i class="fas fa-plus"></i> Adicionar Avião
                        <?php } else {
                        ?>
                            <i class="fas fa-pencil-alt"></i> Editar Avião
                        <?php }
                        ?>
                    </div>
                    <div class="col-md-4">
                        <div class="card-body">
                            <?php if (is_null($airplaneToEdit)) {
                            ?>
                                <form action="<?php echo (Url::toRoute('aviao/criar')); ?>" method="post">
                                <?php } else {
                                ?>
                                    <form action="<?php echo (Url::toRoute('aviao/atualizar', $airplaneToEdit->idaviao));
                                                    ?>" method="post">
                                    <?php }
                                    ?>
                                    <!-- add referencia -->
                                    <div class="form-group">
                                        <label for="referencia">Referência</label>
                                        <input value="<?php if (!is_null($airplaneToEdit)) {
                                                            echo ($airplaneToEdit->referencia);
                                                        }
                                                        ?>" type="text" class="form-control" id="referencia" name="referencia">
                                    </div>
                                    <!-- add lotação -->
                                    <div class="form-group">
                                        <label for="lotacaototal">Lotação</label>
                                        <input value="<?php if (!is_null($airplaneToEdit)) {
                                                            echo ($airplaneToEdit->lotacaototal);
                                                        }
                                                        ?>" type="number" min="0" class="form-control" id="lotacaototal" name="lotacaototal">
                                    </div>
                                    <!-- add tipo avião -->
                                    <div class="form-group">
                                        <label for="tipoaviao">Tipo de Avião</label>
                                        <input value="<?php if (!is_null($airplaneToEdit)) {
                                                            echo ($airplaneToEdit->tipoaviao);
                                                        }
                                                        ?>" type="text" class="form-control" id="tipoaviao" name="tipoaviao">
                                    </div>
                                    <!-- Botao criar/editar -->
                                    <?php if (is_null($airplaneToEdit)) {
                                    ?>
                                        <button type="submit" style="float: right;" class="btn btn-outline-success mb-2">Criar</button>
                                    <?php } else {
                                    ?>
                                        <button type="submit" style="float: right;" class="btn btn-outline-info mb-2">Editar</button>
                                    <?php  }
                                    ?>
                                    </form>
                                </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <!-- Bootstrap core JavaScript-->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="<?= Asset::js('/sb-admin-2.min.js') ?>"></script>

    <!-- Page level plugins -->
    <script src="vendor/chart.js/Chart.min.js"></script>

    <!-- Page level custom scripts -->
    <script src="<?= Asset::js('/demo/chart-area-demo.js') ?>"></script>
    <script src="<?= Asset::js('/demo/chart-pie-demo.js') ?>"></script>

</body>

</html>