<?php

use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Data;

$flights = Data::get('flights');
$flightToEdit = Data::get('flightToEdit');

?>

<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Custom fonts for this template-->
    <link href="<?= Asset::css('/template/fontawesome-free/css/all.min.css') ?>" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,200,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="<?= Asset::css('/template/sb-admin-2.css') ?>" rel="stylesheet">
    <title>FlightTravelAir</title>
</head>

<body>
    <div id="wrapper">
        <!-- Sidebar -->
        <?php Layout::includeLayout('leftbarGestorVoo') ?>

        <div id="content-wrapper" class="d-flex flex-column">
            <div class="container-fluid">

                <!-- Page Heading -->
                <h1 class="h3 mt-3 mb-4 text-gray-800">Voos</h1>

                <!-- mensagens de erro, sucesso e aviso -->
                <?php Layout::includeLayout('mensagens') ?>

                <!-- DataTales Example -->
                <div class="card shadow mb-4">
                    <div class="card-header py-3">
                        <i class="fas fa-list"></i> Lista Voos
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                <thead>
                                    <tr>
                                        <th style="width: 20%">Id Voo</th>
                                        <th style="width: 30%">Descricao</th>
                                        <th style="width: 40%">Preço</th>
                                        <th style="width: 10%">Ações</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php
                                    foreach ($flights as $flight) { ?>
                                        <tr>
                                            <td><?= $flight->idvoo ?></td>
                                            <td><?= $flight->descricao ?></td>
                                            <td><?= $flight->preco ?> €</td>
                                            <td>
                                                <!-- editar -->
                                                <form style="float: left; padding-right: 2px;" action="<?= Url::toRoute('voo/editar', $flight->idvoo) ?>  " method="POST">
                                                    <button class="btn btn-info btn-circle btn-sm" type="submit">
                                                        <i class="fas fa-pencil-alt"></i>
                                                    </button>
                                                </form>
                                                <!-- eliminar -->
                                                <form style="float: left; padding-right: 2px;" action="<?= Url::toRoute('voo/eliminar', $flight->idvoo) ?> " method="POST">
                                                    <button class="btn btn-danger btn-circle btn-sm" type="submit">
                                                        <i class="fas fa-trash-alt"></i>
                                                    </button>
                                                </form>
                                            </td>
                                        </tr>
                                    <?php } ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>

                <!-- ADD VOO -->
                <div class="card shadow mb-4">
                    <div class="card-header py-3">
                        <?php if (is_null($flightToEdit)) { ?>
                            <i class="fas fa-plus"></i> Adicionar Voo
                        <?php } else { ?>
                            <i class="fas fa-pencil-alt"></i> Editar Voo
                        <?php } ?>
                    </div>
                    <div class="col-md-4">
                        <div class="card-body">
                            <!-- CRIAR aeroporto -->
                            <div class="form-group">
                                <?php if (is_null($flightToEdit)) { ?>
                                    <form action="<?php echo (Url::toRoute('voo/criar')); ?>" method="post">
                                    <?php } else { ?>
                                        <form action="<?php echo (Url::toRoute('voo/atualizar', $flightToEdit->idvoo)); ?>" method="post">
                                        <?php } ?>
                            </div>
                            <div class="form-group">
                                <label for="preco">Descrição</label>
                                <input value="<?php if (!is_null($flightToEdit)) {
                                                    echo ($flightToEdit->descricao);
                                                }
                                                ?>" type="text" class="form-control" id="descricao" name="descricao">
                            </div>

                            <!-- add preço -->
                            <div class="form-group">
                                <label for="preco">Preço</label>
                                <input value="<?php if (!is_null($flightToEdit)) {
                                                    echo ($flightToEdit->preco);
                                                }
                                                ?>" type="number" min="0" step="0.01" class="form-control" id="preco" name="preco">
                            </div>
                            <!-- Botao criar/editar -->
                            <?php if (is_null($flightToEdit)) {
                            ?>
                                <button type="submit" style="float: right;" class="btn btn-outline-success mb-2">Criar</button>
                            <?php } else { ?>
                                <button type="submit" style="float: right;" class="btn btn-outline-info mb-2">Editar</button>
                            <?php  } ?>
                            </form>
                        </div>
                    </div>
                </div>



                <!-- Bootstrap core JavaScript-->
                <script src="vendor/jquery/jquery.min.js"></script>
                <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

                <!-- Core plugin JavaScript-->
                <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

                <!-- Custom scripts for all pages-->
                <script src="<?= Asset::js('/sb-admin-2.min.js') ?>"></script>

                <!-- Page level plugins -->
                <script src="vendor/chart.js/Chart.min.js"></script>

                <!-- Page level custom scripts -->
                <script src="<?= Asset::js('/demo/chart-area-demo.js') ?>"></script>
                <script src="<?= Asset::js('/demo/chart-pie-demo.js') ?>"></script>

</body>

</html>