<?php

use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Data;

$tickets = Data::get('tickets');

?>

<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Custom fonts for this template-->
    <link href="<?= Asset::css('/template/fontawesome-free/css/all.min.css') ?>" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,200,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="<?= Asset::css('/template/sb-admin-2.css') ?>" rel="stylesheet">
    <title>FlightTravelAir</title>
</head>

<body>
    <div id="wrapper">
        <!-- Sidebar -->
        <?php
        Layout::includeLayout('leftbarPassageiro')
        ?>
        <div id="content-wrapper" class="d-flex flex-column">
            <div class="container-fluid">
                <h1 class="h3 mt-3 mb-4 text-gray-800">Passagens</h1>
                <div class="card shadow mb-4">
                    <div class="card-header py-3">
                        <i class="fas fa-list"></i> Lista Passagens
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                <thead>
                                    <tr>
                                        <th style="width: 5%">Id</th>
                                        <th style="width: 30%">Ida</th>
                                        <th style="width: 30%">Volta</th>
                                        <th style="width: 15%">Data Compra</th>
                                        <th style="width: 10%">Preço</th>
                                        <th style="width: 3%">Checkin</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php
                                    foreach ($tickets as $ticket) {
                                    ?>
                                        <tr>
                                            <td><?= $ticket->idpassagem ?></td>
                                            <td><?= $ticket->ida ?></td>
                                            <?php if (strcmp($ticket->ida, $ticket->volta) == 0) { ?>
                                                <td>-</td>
                                            <?php } else { ?>
                                                <td><?= $ticket->volta ?></td>
                                            <?php } ?>
                                            <td><?= $ticket->dataCompra->format('Y-m-d h:i') ?></td>
                                            <td><?= $ticket->preco ?> €</td>
                                            <?php if ($ticket->checkin == 1) { ?>
                                                <td> ✔ </td>
                                            <?php } else { ?>
                                                <td> ❌ </td>
                                            <?php } ?>
                                        <?php } ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>